In [1]:
import torch
import numpy

## Tensors

In [2]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[1, 2], [3, 4], [5, 6]])
c = torch.FloatTensor([1, 2, 3, 4])
d = torch.DoubleTensor([2, 3, 4])

In [3]:
a, b, c, d

(tensor([1, 2, 3]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([1., 2., 3., 4.]),
 tensor([2., 3., 4.], dtype=torch.float64))

In [5]:
c = torch.tensor([1, 2, 3, 4], dtype=torch.float)
c

tensor([1., 2., 3., 4.])

In [7]:
d = torch.tensor([2, 3, 4], dtype=torch.double)
d

tensor([2., 3., 4.], dtype=torch.float64)

In [10]:
print(b.shape)
print(b.size())

torch.Size([3, 2])
torch.Size([3, 2])


In [11]:
b.view(1, -1)

tensor([[1, 2, 3, 4, 5, 6]])

In [12]:
b.view(2, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 3, 4])
result = torch.add(a, b)
print(result)

tensor([3, 5, 7])


In [14]:
print(a + b)

tensor([3, 5, 7])


In [17]:
print(b)
b.add(a)
print(b)
b.add_(a)
print(b)

tensor([2, 3, 4])
tensor([2, 3, 4])
tensor([3, 5, 7])


In [19]:
print(b.numel())
print(torch.numel(b))

3
3


In [20]:
print(b.size())
print(b.shape)

torch.Size([3])
torch.Size([3])


In [29]:
x = torch.ones(2, 3, dtype=torch.double)
print(x)
print(x.shape)
print(x.size()[0])
print(x.size()[1])
print(x.shape[0])
print(x.shape[1])

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.Size([2, 3])
2
3
2
3


In [38]:
x = torch.tensor([1, 2, 3])
y = x.numpy()
print(x, y)
x.add_(1)
print("After change:")
print(x, y)

tensor([1, 2, 3]) [1 2 3]
After change:
tensor([2, 3, 4]) [2 3 4]


In [39]:
x = torch.tensor([1, 2, 3])
y = x.numpy()
print(x, y)
x = x + 1
print("After change:")
print(x, y)

tensor([1, 2, 3]) [1 2 3]
After change:
tensor([2, 3, 4]) [1 2 3]


In [40]:
x = torch.tensor([1, 2, 3])
y = x.numpy().copy()
print(x, y)
x.add_(1)
print("After change:")
print(x, y)

tensor([1, 2, 3]) [1 2 3]
After change:
tensor([2, 3, 4]) [1 2 3]


In [43]:
# From numpy array to tensor
x = numpy.array([1, 2, 3])
y = torch.from_numpy(x)
print(x, y)
x[0] = 100
print("After change:")
print(x, y)

[1 2 3] tensor([1, 2, 3], dtype=torch.int32)
After change:
[100   2   3] tensor([100,   2,   3], dtype=torch.int32)


In [46]:
# From numpy array to tensor eliminating shared storage
x = numpy.array([1, 2, 3])
y = torch.from_numpy(x).clone()
print(x, y)
x[0] = 100
print("After change:")
print(x, y)

[1 2 3] tensor([1, 2, 3], dtype=torch.int32)
After change:
[100   2   3] tensor([1, 2, 3], dtype=torch.int32)


In [54]:
x = torch.tensor([1, 2, 3, 4, 5], dtype = torch.float64)
x.unsqueeze_(1)
x

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]], dtype=torch.float64)

In [76]:
import torch.nn as nn
from torch.nn import Module
model = Module()
model.fg1 = nn.Linear(5, 4)
model.dg1 = nn.Linear(4, 3)
model.fc3 = nn.Linear(3, 1)
for parameter in model.parameters():
    print(parameter.shape)

torch.Size([4, 5])
torch.Size([4])
torch.Size([3, 4])
torch.Size([3])
torch.Size([1, 3])
torch.Size([1])
